# Generated by Django 3.2.6 on 2022-11-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tguser',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='tguser',
            old_name='user_ud',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='tguser',
            name='chat_id',
            field=models.BigIntegerField(unique=True, verbose_name='Chat ID'),
        ),
    ]
